### ISSUE TITLE
Enable Neos 5.0

### ISSUE THREAD

**Issue by rr-appadaptive** [jonnitto/Carbon.Link#3]
I tried - successfully - to install Neos from scratch yesterday. The installation of a skeleton-site as recommended by the neos-team did not work though because the necessary helper-package carbon/link cannot be installed for Neos 5.0

**Comment by jonnitto** [comment]
Solved with version [1.4.1](https://github.com/CarbonPackages/Carbon.Link/releases/tag/1.4.1)
