### ISSUE TITLE
How to add data-attributes on Carbon.Link?

### ISSUE THREAD

**Issue by dkoether** [jonnitto/Carbon.Link#5]
Hello,

I'm trying to learn how to get custom data-attributes directly on the generated anchor element of Carbon.Link but couldn't figure it out, yet. 

Do you know how to add them or am I right that there must be some kind of restriction?

Best regards and thanks in advance!

**Comment by jonnitto** [comment]
You could use the `Neos.Fusion:Augmenter` or set the attribute like this:

```html
<Carbon.Link:Link attributes.data-foo="bar">Content</Carbon.Link:Link>
```

**Comment by dkoether** [comment]
Thank you, @jonnitto! That works! 😃
